baseURL = "https://nishalsach.github.io/"
languageCode = "en-us"
title = "Sachita Nishal"
theme = "ezhil"
# Number of posts to show in recent posts list (Optional). Defaults to 10.
paginate = 3

publishDir = ".."
# relativeURLs = true

# Enable syntax highlighting.
# Guides: https://xyproto.github.io/splash/docs/all.html
# https://discourse.gohugo.io/t/pygmentsstyle/20785
# Make sure these stting are BEFORE any arrays
pygmentsuseclasses = false
pygmentscodefences = true
pygmentsstyle = "monokailight"
pygmentscodefencesguesssyntax = true

# To enable images with HTML tags (for greater flexibility)
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true

# Number of characters to show in summary.
summaryLength = 20

[params]
    # Blog subtitle which appears below blog title. Supports markdown.
    subtitle = "3rd-Year PhD Student, Northwestern University"

    # Content types which are included in home page recent posts list.
    mainSections = ["posts", "research"]

    # Content types which are excludes Disqus comments.
    disableDisqusTypes = ["page"]

    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
    featherIconsCDN = true

    # Specify favicon (icons/i.png maps to static/icons/i.png). No favicon if not defined.
    favicon = "icons/myicon.png"

    # Switch to dark mode or auto detect mode from OS (Optional).
    # "dark" will set mode to dark and "auto" will switch to dark mode if OS is in dark mode.
    #mode = "dark" # "dark" or "auto"

    # Custom CSS added to default styles. Files added to `static` folder is copied as it is to
    # root by Hugo. For example if you have custom CSS file under `static/css/custom.css` then
    # you can specify custom css path as `css/custom.css`.
    customCSS = "css/custom.css"
    # Custom CSS added to dark mode style.
    customDarkCSS = "css/custom-dark.css"

    # Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
    customJS = ["js/abc.js", "js/xyz.js", "https://code.jquery.com/jquery-3.4.1.js"]

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

#[[menu.main]]
#name = "About Me"
#url = "/about"
#weight = 2

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 2

[[menu.main]]
name = "Publications"
url = "/publications"
weight = 3

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 4

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 3

#[[menu.main]]
#name = "Cool Stuff"
#url = "/cool_stuff/2020-06-16-cool-stuff/"
#weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).

[[params.social]]
name = "Google Scholar"
icon = "pen-tool"
url = "https://scholar.google.com/citations?user=JgsaeQmLjKcC&hl=en&oi=ao"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/nishalsach"

[[params.social]]
name = "Gmail"
icon = "mail"
url = "mailto:nishal@u.northwestern.edu"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nishalsach"

#[[params.social]]
#name = "Spotify"
#icon = "music"
#url = "https://open.spotify.com/user/parikalpanaa"

# Enable tags.
[taxonomies]
   tag = "tags"
